### ISSUE TITLE
搭建好之后不能登陆的问题

### ISSUE THREAD

**Issue by hadesleejs** [TeamcatCorp/ETeam#2]
搭建好之后不能登陆，我看了MySQL的表，数据已经导入了，请问我还应该去查一下哪个？谢谢
<img width="670" alt="_20181203092745" src="https://user-images.githubusercontent.com/7189444/49348009-b7673600-f6dd-11e8-8ec1-de4036a2b147.png">

**Comment by skyzhang2006** [comment]
你查看一下是不是你的数据库访问对IP和用户做了限制，另外就是你看看在settings文件里面配置的用户名，密码，还有数据库的ip,端口对不对

**Comment by skyzhang2006** [comment]
935995216 这是qq技术支持群，在哪里反馈问题会得到及时的回复
