### ISSUE TITLE
无法输入产品线

### ISSUE THREAD

**Issue by hdylysk** [TeamcatCorp/ETeam#4]
在创建项目页面，产品线的位置无法输入自定义的名称

**Comment by skyzhang2006** [comment]
目前没有提供直接输入产品线的页面，临时可以直接在product表里添加你需要的产品线。建议你加群，哪里反馈更快

**Comment by hdylysk** [comment]
> 目前没有提供直接输入产品线的页面，临时可以直接在product表里添加你需要的产品线。建议你加群，哪里反馈更快

如何加入群？
